name: Spring Tester CI
on:
  push:
    branches: [“main”,”master”,”dev”]
  pull_request:
    branches: ["main",”master”,”dev”]
jobs:
  build:
    runs-on: mac-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build eith Maven
        run: mvn clean install
